/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

  import java.sql.Connection;
  import java.sql.PreparedStatement;
  import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Nimra Sajid
 */
public class UserProfile extends javax.swing.JFrame {

       Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    /**
     * Creates new form UserProfile
     */
    public UserProfile() {
        initComponents();
    }

    public UserProfile(String name) {
        initComponents();
        label1.setText(name);
      
    }
    
   
   
    
    
    
     
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back_Button = new javax.swing.JButton();
        P_Head1 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        P_Left = new javax.swing.JPanel();
        Profile = new javax.swing.JButton();
        RentBike = new javax.swing.JButton();
        ReturnBike = new javax.swing.JButton();
        RentedBikes = new javax.swing.JButton();
        ReturnedMovies = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        P_Head1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        heading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("User Profile");

        javax.swing.GroupLayout P_Head1Layout = new javax.swing.GroupLayout(P_Head1);
        P_Head1.setLayout(P_Head1Layout);
        P_Head1Layout.setHorizontalGroup(
            P_Head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Head1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );
        P_Head1Layout.setVerticalGroup(
            P_Head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Head1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        P_Left.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Profile.setText("Profile");
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        RentBike.setText("Rent a Bike");
        RentBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentBikeActionPerformed(evt);
            }
        });

        ReturnBike.setText("Return a Bike");
        ReturnBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBikeActionPerformed(evt);
            }
        });

        RentedBikes.setText(" Bikes Currently Renting");
        RentedBikes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentedBikesActionPerformed(evt);
            }
        });

        ReturnedMovies.setText("Returned Bikes");
        ReturnedMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnedMoviesActionPerformed(evt);
            }
        });

        label1.setText("label1");

        jLabel4.setText("Username:");

        javax.swing.GroupLayout P_LeftLayout = new javax.swing.GroupLayout(P_Left);
        P_Left.setLayout(P_LeftLayout);
        P_LeftLayout.setHorizontalGroup(
            P_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RentBike, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReturnBike, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RentedBikes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReturnedMovies, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addGroup(P_LeftLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        P_LeftLayout.setVerticalGroup(
            P_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(Profile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RentBike)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnBike)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RentedBikes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnedMovies)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(P_Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_Head1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Back_Button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_Head1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(P_Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(Back_Button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed

     
          
      //    UserInfo Obj = new UserInfo();
      //     Obj.setVisible(true);
       
             
         //   userinfo.setVisible(true);
         //    setVisible(false);
      
         
        
        
    }//GEN-LAST:event_ProfileActionPerformed

    private void RentBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentBikeActionPerformed
      
        
        /*
        
          String fullname =  label1.getText();
      
      
  
    
        
     try {
         con = DBConnection.getConnection();
         pst = con.prepareStatement("select * from ADDUSER where fullname=?");
         pst.setString(1, fullname);
         
         rs = pst.executeQuery();
         
         if(rs.next()){
             
             
             String dbfullname = rs.getString("fullname");
             
             
            LoanBike1 loanbike1 = new LoanBike1(dbfullname);
            
                     
             
            
          // UserProfile.setVisible(true);
          // setVisible(false);
          
        
             
            loanbike1.setVisible(true);
             setVisible(false);
         }
         
         
     } catch(Exception ex){
         System.out.println(""+ex);
     }
        
        */
       
     
        
      LoanBike1 Obj = new LoanBike1();
      Obj.setVisible(true);
        
        
    }//GEN-LAST:event_RentBikeActionPerformed

    private void ReturnBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBikeActionPerformed

      ReturnBike Obj = new ReturnBike();
      Obj.setVisible(true);
        
        
        
    }//GEN-LAST:event_ReturnBikeActionPerformed

    private void RentedBikesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentedBikesActionPerformed
   
        
      CurrentBikesRenting Obj = new CurrentBikesRenting();
      Obj.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_RentedBikesActionPerformed

    private void ReturnedMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnedMoviesActionPerformed

         CurrentBikesReturned Obj = new CurrentBikesReturned();
      Obj.setVisible(true);
        
        
        
    }//GEN-LAST:event_ReturnedMoviesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JPanel P_Head1;
    private javax.swing.JPanel P_Left;
    private javax.swing.JButton Profile;
    private javax.swing.JButton RentBike;
    private javax.swing.JButton RentedBikes;
    private javax.swing.JButton ReturnBike;
    private javax.swing.JButton ReturnedMovies;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel4;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
